from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class Message(BaseModel):
    message: str = Field(..., description="Informational message.")


class GameCreate(BaseModel):
    player_x: str = Field("Player X", description="Username for player X.")
    player_o: str = Field("Player O", description="Username for player O.")


class GameOut(BaseModel):
    id: str = Field(..., description="Game identifier.")
    board: List[Literal["", "X", "O"]] = Field(
        ..., min_length=9, max_length=9, description="Board cells list of 9 items."
    )
    current_player: Optional[Literal["X", "O"]] = Field(
        None, description="Which player should move next."
    )
    players: Dict[Literal["X", "O"], str] = Field(
        ..., description="Mapping from symbol to username."
    )
    status: Literal["in_progress", "x_won", "o_won", "draw"] = Field(
        "in_progress", description="Current game status."
    )
    moves: List[dict] = Field(default_factory=list, description="Move history.")
    created_at: datetime = Field(..., description="Creation timestamp.")


class MoveRequest(BaseModel):
    position: int = Field(..., ge=0, le=8, description="Board index (0..8).")
    player: Literal["X", "O"] = Field(..., description="Player making the move.")


class MoveResponse(BaseModel):
    game: GameOut = Field(..., description="Updated game state.")
    status_message: str = Field(..., description="Status message after the move.")


class PlayerScore(BaseModel):
    username: str = Field(..., description="Player username.")
    score: int = Field(..., ge=0, description="Player score.")


class PlayerScoreUpdate(BaseModel):
    score: int = Field(..., ge=0, description="New score value to set for the player.")


class ChatRequest(BaseModel):
    message: str = Field(..., description="User chat message.")
    game_id: Optional[str] = Field(
        None, description="Optional game id to provide context for trash talk."
    )
    username: Optional[str] = Field(None, description="Optional username context.")


class ChatResponse(BaseModel):
    reply: str = Field(..., description="Trash talk reply generated by the AI.")
